services:
  - type: web
    name: fitzone-backend
    env: docker
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: DATABASE_URL
        fromDatabase:
          name: fitzone-db
          property: connectionString
    port: 10000

databases:
  - name: fitzone-db
    databaseName: fitzone
    plan: free